// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
       // return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT_-3XrBhOJovxhB-v4OL2rOCGMjb8QIo',
    appId: '1:855184812837:android:f29c7616e3f6e11eba88cc',
    messagingSenderId: '855184812837',
    projectId: 'mental-health-30ee1',
    databaseURL: 'https://mental-health-30ee1-default-rtdb.firebaseio.com',
    storageBucket: 'mental-health-30ee1.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyATOnL8hn7FrszUphI4ri1gbWiJSlPAWkg',
  //   appId: '1:31312698661:ios:36ac32bbce25e3ec84cecc',
  //   messagingSenderId: '31312698661',
  //   projectId: 'autism-62a1a',
  //   storageBucket: 'autism-62a1a.appspot.com',
  //   databaseURL: 'https://autism-62a1a-default-rtdb.firebaseio.com',
  //   iosBundleId: 'com.techkor.autism.RunnerTests',
  // );
  //
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAwa9EgQjV7zJWEljOYcWJRBn8Iow7InSo",
      authDomain: "mental-health-30ee1.firebaseapp.com",
      databaseURL: "https://mental-health-30ee1-default-rtdb.firebaseio.com",
      projectId: "mental-health-30ee1",
      storageBucket: "mental-health-30ee1.firebasestorage.app",
      messagingSenderId: "855184812837",
      appId: "1:855184812837:web:67f3ce1279c945a8ba88cc",
      measurementId: "G-L43SSK082J"
  );
}
